spring.application.name=backendcouncil-api
spring.datasource.url=jdbc:postgresql://localhost:5432/SysRep
spring.datasource.username=usuario
spring.datasource.password=2009psp2
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
springdoc.api-docs.path=/v1/api-docs/
springdoc.swagger-ui.configUrl=/v1/api-docs/swagger-config
springdoc.swagger-ui.path=/docs-api.html